source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'PKActivityIndicator_Example', :exclusive => true do
  pod "PKActivityIndicator", :path => "../"
end

target 'PKActivityIndicator_Tests', :exclusive => true do
  pod "PKActivityIndicator", :path => "../"

  
end
